version: '3'
services:
  ha-homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/htpc/Desktop/home-automation/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  ha-unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    volumes:
      - /home/htpc/Desktop/home-automation/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
  ha-nginx:
    container_name: nginx
    image: "nginx:latest"
    volumes:
      - /home/htpc/Desktop/home-automation/nginx-reverse-proxy/homeassistant.conf:/etc/nginx/conf.d/homeassistant.conf:ro
    restart: always
    network_mode: host
networks:
  homeautomation:
